# Generated by Django 4.2.13 on 2024-06-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('year', models.PositiveBigIntegerField()),
                ('journal', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='labmember',
            name='position',
            field=models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AL', 'Alumni'), ('PI', 'Principle Investigator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='title',
            field=models.CharField(choices=[('Ph.D Student', 'Ph.D Student'), ('Ph.D Candidate', 'Ph.D Candidate'), ('Ph.D', 'Ph.D'), ('Principle Investigator', 'Principle Investigator')], max_length=22, null=True),
        ),
    ]
