# Generated by Django 4.2.13 on 2024-06-03 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_publication_alter_labmember_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
