# Generated by Django 4.2.13 on 2024-06-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_publication_issue_publication_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='issue',
        ),
        migrations.AddField(
            model_name='publication',
            name='Issue',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
