# Generated by Django 4.2.13 on 2024-06-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_publication_issue_publication_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
