# Generated by Django 4.2.13 on 2024-06-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_publication_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
