# Generated by Django 4.2.13 on 2024-06-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_publication_journal_alter_publication_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
