# Generated by Django 4.2.13 on 2024-06-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_card_delete_scrollimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='detail',
            new_name='description',
        ),
    ]
