# Generated by Django 4.2.13 on 2024-06-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_funding'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='content_images/')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
