# Generated by Django 4.2.13 on 2024-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fundingimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='position',
            field=models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AL', 'Alumni'), ('PI', 'Principal Investigator')], max_length=2),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='title',
            field=models.CharField(choices=[('Ph.D Student', 'Ph.D Student'), ('Ph.D Candidate', 'Ph.D Candidate'), ('Ph.D', 'Ph.D'), ('Principal Investigator', 'Principal Investigator')], max_length=22, null=True),
        ),
    ]
