# Generated by Django 4.2.13 on 2024-07-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_researchsection_research_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='employer',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='labmember',
            name='year_finished',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='year_joined',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
