# Generated by Django 4.2.13 on 2024-08-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_labmember_employer_labmember_year_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='position',
            field=models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PD', 'Post Doc')], max_length=2),
        ),
        migrations.AlterField(
            model_name='labmember',
            name='title',
            field=models.CharField(blank=True, choices=[('MS', 'Masters'), ('Ph.D Student', 'Ph.D Student'), ('Ph.D Candidate', 'Ph.D Candidate'), ('Ph.D', 'Ph.D'), ('Principal Investigator', 'Principal Investigator')], max_length=22, null=True),
        ),
    ]
