# Generated by Django 4.2.13 on 2024-08-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_labmember_position_alter_labmember_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='position',
            field=models.CharField(blank=True, choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PD', 'Post Doc')], max_length=2, null=True),
        ),
    ]
