# Generated by Django 4.2.13 on 2024-10-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_labmember_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='title',
            field=models.CharField(blank=True, choices=[('Undergrad', 'Undergraduate'), ('MS', 'Masters'), ('Ph.D Student', 'Ph.D Student'), ('Ph.D Candidate', 'Ph.D Candidate'), ('Ph.D', 'Ph.D'), ('Principal Investigator', 'Principal Investigator')], max_length=22, null=True),
        ),
    ]
