# Generated by Django 4.2.13 on 2024-11-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_card_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
