# Generated by Django 4.2.13 on 2025-01-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_publication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='title',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('MSS', 'M.S. Student'), ('PhD Student', 'Ph.D Student'), ('PhD Candidate', 'Ph.D Candidate'), ('M.S.', 'M.S.'), ('PhD', 'Ph.D'), ('Principal Investigator', 'Principal Investigator')], max_length=22, null=True),
        ),
    ]
