# Generated by Django 4.2.13 on 2025-02-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_labmember_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('embeded_link', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='labmember',
            name='title',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('M.S. Student', 'M.S. Student'), ('Ph.D Student', 'Ph.D Student'), ('Ph.D Candidate', 'Ph.D Candidate'), ('M.S.', 'M.S.'), ('Ph.D', 'Ph.D'), ('Principal Investigator', 'Principal Investigator')], max_length=22, null=True),
        ),
    ]
