# Generated by Django 4.2.13 on 2025-02-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_hiringposition_alter_labmember_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringposition',
            name='link',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='hiringposition',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
