# Generated by Django 4.2.13 on 2025-02-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_hiringposition_link_alter_hiringposition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringposition',
            name='link',
        ),
    ]
