# Generated by Django 4.2.13 on 2025-03-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_funding_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingimg',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
