# Generated by Django 4.2.13 on 2025-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_fundingimg_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDocHelpLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('link', models.CharField(max_length=15000)),
            ],
        ),
    ]
