# Generated by Django 4.2.13 on 2025-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_postdochelplinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdochelplinks',
            name='link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='postdochelplinks',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
