# Generated by Django 4.2.13 on 2025-05-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_postdochelplinks_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdochelplinks',
            name='due_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
