# Generated by Django 4.2.13 on 2025-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_postdochelplinks_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostDocHelpLinks',
            new_name='PostDocHelpLink',
        ),
    ]
