# Generated by Django 4.2.13 on 2024-05-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('PS', 'Ph.D Student'), ('PC', 'Ph.D Candidate')], max_length=2, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lab_member_images/')),
                ('year_joined', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AL', 'Alumni')], max_length=2)),
                ('is_alumni', models.BooleanField(null=True)),
            ],
        ),
    ]
